# Generated by Django 2.2.12 on 2020-06-24 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which  the object was created', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which  the object was last modified', verbose_name='Modified at')),
                ('name', models.CharField(max_length=140, verbose_name='Circle name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(blank=True, max_length=255, verbose_name='Circle description')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/picture')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False, help_text='Verified circle, only yes is official', verbose_name='Verified circle')),
                ('is_public', models.BooleanField(default=True, verbose_name='Circle public')),
                ('is_limit', models.BooleanField(default=False, verbose_name='Limit of circle')),
                ('members_limit', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which  the object was created', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which  the object was last modified', verbose_name='Modified at')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('used', models.BooleanField(default=False, help_text='Invitación usada?')),
                ('used_at', models.DateTimeField(blank=True, help_text='Fecha de uso', null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which  the object was created', verbose_name='Created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which  the object was last modified', verbose_name='Modified at')),
                ('is_admin', models.BooleanField(default=False, help_text='If is admin of the circle', verbose_name='Circle admin')),
                ('user_invitations', models.PositiveIntegerField(default=0, help_text='Invitaciones usadas')),
                ('remaining_invitation', models.PositiveIntegerField(default=0, help_text='Invitaciones que te quedan')),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('is_activate', models.BooleanField(default=True, verbose_name='Active status')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circles.Circle')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
