# Generated by Django 2.2.12 on 2020-06-24 19:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('circles', '0002_auto_20200624_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='offered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ride',
            name='offered_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='circles.Circle'),
        ),
        migrations.AddField(
            model_name='ride',
            name='passengers',
            field=models.ManyToManyField(related_name='passengers', to=settings.AUTH_USER_MODEL),
        ),
    ]
